version: '3.5'

services:
  kurashi_frontpage:
    container_name: kurashi_frontpage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
networks:
  kurashi_frontpage:
    driver: bridge
